FROM docker:24.0.4-dind as build

ARG KIND_VERSION=v0.20.0

RUN apk add --no-cache go=1.20.10-r0 \
    && go install "sigs.k8s.io/kind@${KIND_VERSION}"

FROM docker:24.0.4-dind as base

COPY --from=build /root/go/bin/kind /usr/local/bin/kind

RUN apk add --no-cache ca-certificates=20230506-r0 \
    gettext=0.21.1-r7 \
    bash=5.2.15-r5

WORKDIR /app

COPY kind.yaml /app/kind.yaml

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]

# Default kube api port and nginx config serving port
EXPOSE 8443 10080
